export enum ORDER_STATUS {
  SEOER_ORDER = 'SEOER_ORDER',
  CONFIRMED_BY_TEAM_LEADER = 'CONFIRMED_BY_TEAM_LEADER',
  REJECTED_BY_TEAM_LEADER = 'REJECTED_BY_TEAM_LEADER',
  CANCELLED_BY_SEOER = 'CANCELLED_BY_SEOER',
  CONFIRMED_BY_PARTNER = 'CONFIRMED_BY_PARTNER',
  COMPLETED_BY_PARTNER = 'COMPLETED_BY_PARTNER',
  CONFIRMED_COMPLETION_BY_SEOER = 'CONFIRMED_COMPLETION_BY_SEOER',
  PAYMENT_APPROVED_BY_MANAGER = 'PAYMENT_APPROVED_BY_MANAGER',
  CANCELLED_BY_MANAGER = 'CANCELLED_BY_MANAGER',
  PAID_BY_MANAGER = 'PAID_BY_MANAGER',
}

export enum ORDER_HISTORY_TYPE {
  CREATE_ORDER = 'CREATE_ORDER',
  CHANGE_STATUS = 'CHANGE_STATUS',
  PRICE_ADJUSTMENT = 'PRICE_ADJUSTMENT',
  PRICE = 'PRICE',
  REMOVE_ORDER_DETAIL = 'REMOVE_ORDER_DETAIL',
}

export const ORDER_STATUS_LALID = [
  ORDER_STATUS.SEOER_ORDER,
  ORDER_STATUS.CONFIRMED_BY_TEAM_LEADER,
  ORDER_STATUS.CONFIRMED_BY_PARTNER,
  ORDER_STATUS.COMPLETED_BY_PARTNER,
  ORDER_STATUS.CONFIRMED_COMPLETION_BY_SEOER,
  ORDER_STATUS.PAYMENT_APPROVED_BY_MANAGER,
  ORDER_STATUS.PAID_BY_MANAGER,
];
