export enum TEAM_MEMBER_ROLE {
  LEADER = 'LEADER',
  VICE_LEADER = 'VICE_LEADER',
  MEMBER = 'MEMBER',
}

export enum TEAM_KEY {
  TEAM_1_NEW = 'TEAM_1_NEW',
  TEAM_1 = 'TEAM_1',
  TEAM_2 = 'TEAM_2',
  TEAM_3 = 'TEAM_3',
  TEAM_PBN = 'TEAM_PBN',
}
