export enum ROLE {
  SUPER_ADMIN = 'SUPER_ADMIN',
  SEOER = 'SEOER',
  MANAGER = 'MANAGER',
  PARTNER = 'PARTNER',
  ASSISTANT = 'ASSISTANT',
  TEAM_LEADER = 'TEAM_LEADER',
  VICE_TEAM_LEADER = 'VICE_TEAM_LEADER',
  DOMAIN_BUYER = 'DOMAIN_BUYER',
}
